language: python
python:
  - 3.6.7
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=api tests/ -v
after_success:
  - coveralls

deploy:
  provider: heroku
  api_key:
    secure: p2NfcjVdi6EBtSIHPg5EHuuOLmgA8uW7LtymF/Vs1ov2lwRBB5XhDpcPR4+jQD3z+qBcndrjrfpW9iLkUyBNZsKXzj045GMcNKWrNMQS3qhbS6YSLQaqkELqsv3EgvkQHm3Vs0k8uzKM8H2uEWiBOuvg/G3oXGXDKYmAZk5eoKaoddXBOSu0qqEfjpBOK7LBoNX9wQ/ttYWAGJey+39EsOEP3PtaXSTKvitI2+B55BX/b3cbPT+FvwC24ON6HsKInsWZGy8MWl9r9tDt5Mn2mmaONYoBk7KcC9Hy0wsMjVCN1nLqYPXhyCG75Bxk+SSd8t3uWbyFB8Auh0nZ3F0Jy2q9xPcw2cim5n/QJYyTwwkVWtJS6NqnLVyiwl4mhlM4bGN9M1aRFU3p5lu0Yux7pfwH/hpOJCh0UE+CZhbArkIvOnghPozhM5ShWkcA3b94RiP7BXiiToK9j0YI2WwR+ZGVjp4v4nyQmxF/h6OanijKLLyp9GRWDItc3Q4ZCP6gtpxpRicm9QOyb2Ahoslp8zcQ4m6qHkB7p4uRBSBTIjH74t29nEC9sIAsRszEBX8ptRXp5Oa+r6kQy3QAlfy0SFHAj80MTkXPMG0iP1emr37CbM2LeKHLhdt5QLZUMADP6m+cFiaxHImMVQc6TloLAungGrtEGLOfWgwxW247Jcc=
  on:
    branch: develop
