language: python
python:
- 3.6.7
install:
- pip install -r requirements.txt
script:
- pytest --cov=api tests/ -v
after_success:
- coveralls
env:
  global:
    secure: hnFBWF4MsvGBsi06ExtTs6PmgxSWqDE9ZfYP0T0ut2AVHZQ5qykazYkbcSM6GWg48YZ7gzPgpTfe36mM4i6tMvjlnUi3OKvBpV69zqZEg5OHsrOqjBvf4+GHwNmmr3weDn/1uNloZW3Qh5pX/5cKNdFb3nGpF+TN+jOMALpRkK2j1lQ0rFIGi1IrCUYTUsq5mTmNguQpBeyEtzJqpDXKhtJEV8/ZFJPN/v3VOeo/6mmrJWY/z1Ddawlxm1ogcgXsRcAafsjx3WJOyXWUcchceawyg+m1EKCN8tNVdmdbBL5Iu5/KVOBAyHU8vORzJFngmM724+0NiT0to6o6OFxeTAb6dPiWkSe3pxjynifxD7wFbVYB5G3a4wvvLvc1l01CCAQjDdQspVInQwdC3aNvA6JLJBPW+eb2jB3mnqyAe9ovOM8TYQc/pc3xLWDk9UEdC0SYVZOJgYhooQYH7XQNYNIvYkcfTMc9+SEAiR9i85PYEnHNOP5yevPKw3O0AQn36W4ERplO4ofrUi1pJLilfbeY2nVRK+4hchCPEWTdU0HJyXCrMzKHpypNNNLZMzynOjU3MMeTt6aSPWlnLd/xn1nlYGDWfy5E9466H3rMCZ1LndNg/xBVhfDTzEWHZ1GXRg0UnmGk7ufM2qLbyAdXKqhCKMw9kDvNz0+YtE0MuNw=
